// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrvlzwdsanuwwfcptttw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpydmx6d2RzYW51d3dmY3B0dHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTQ0MzEsImV4cCI6MjA2OTM3MDQzMX0.taDWoEKmmPvbrTt524lmWr2PwV9cdxLFid1ZMXTIFEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});